services:

  sine:
    image: ghcr.io/blacklizardcode/sine:latest
    container_name: sine
    restart: always
    environment:
      - JWT_KEY=smtn
      - DB_USER=root
      - DB_PASS=root
      - DB_URI=127.0.0.1:5432
      - DB_NAME=sine-db

  postgres:
    image: postgres
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: sine-db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data: